[package]
name = "psctl"
version = "0.1.3"
edition = "2021"
description = "An operator for local processes"
repository = "https://github.com/bww/psctl"
readme = "README.md"
license = "BSD-3-Clause"

[dependencies]
clap = { version="3.1", features=["derive"] }
tokio = { version = "1", features = ["full"] }
reqwest = { version = "0.11" }
futures = { version = "0.3.26" }
url = { version = "2.3.1" }
